# Generated by Django 4.2 on 2023-05-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='date',
            new_name='year',
        ),
        migrations.AddField(
            model_name='load',
            name='img',
            field=models.ImageField(default='02-11-2022', upload_to=''),
            preserve_default=False,
        ),
    ]
