# Generated by Django 4.2 on 2023-05-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_load_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='img',
            field=models.ImageField(upload_to='gallary'),
        ),
    ]
